import { User, EncryptedBankDetails, Transaction, RiskLevel, VerificationIncident, Notification } from '../types';

interface Database {
    users: User[];
    bankDetails: EncryptedBankDetails[];
    transactions: Transaction[];
    verificationIncidents: VerificationIncident[];
    notifications: Notification[];
}

const generatePastDate = (daysAgo: number, hour?: number, minute?: number) => {
    const date = new Date();
    date.setDate(date.getDate() - daysAgo);
    if (hour !== undefined) date.setHours(hour);
    if (minute !== undefined) date.setMinutes(minute);
    return date.toISOString();
};

// Simulated password hashes (in a real app, these are generated by bcrypt)
const mockHashes = {
    user1: 'bcrypt_sim_salt123_cGFzc3dvcmQxMjM=', // password123
    user2: 'bcrypt_sim_salt456_cGFzc3dvcmQ0NTY=', // password456
    user3: 'bcrypt_sim_salt789_cGFzc3dvcmQ3ODk=', // password789
    user4: 'bcrypt_sim_saltABC_cGFzc3dvcmRBQkM=', // passwordABC
    user5: 'bcrypt_sim_saltDEF_cGFzc3dvcmRERUY=', // passwordDEF
    user6: 'bcrypt_sim_saltGHI_cGFzc3dvcmRHSEk=', // passwordGHI
    user7: 'bcrypt_sim_saltJKL_cGFzc3dvcmRKS0w=', // passwordJKL
    user8: 'bcrypt_sim_saltMNO_cGFzc3dvcmRNTk8=', // passwordMNO
}

const db: Database = {
    users: [
        { id: 'user-1', name: 'Rohan Sharma', dob: '1995-08-15', mobile: '9876543210', email: 'rohan.sharma@email.com', passwordHash: mockHashes.user1, status: 'ACTIVE', faceReferenceImages: [], createdAt: generatePastDate(365), adminNotes: [] },
        { id: 'user-2', name: 'Priya Patel', dob: '1992-03-22', mobile: '9123456789', email: 'priya.patel@email.com', passwordHash: mockHashes.user2, status: 'ACTIVE', faceReferenceImages: [], createdAt: generatePastDate(730), adminNotes: [] },
        { id: 'user-3', name: 'Amit Singh', dob: '1988-11-10', mobile: '9988776655', email: 'amit.singh@email.com', passwordHash: mockHashes.user3, status: 'BLOCKED', faceReferenceImages: [], createdAt: generatePastDate(120), adminNotes: ["Account blocked due to multiple high-risk transaction attempts."] },
        { id: 'user-4', name: 'Sunita Rao', dob: '2000-01-30', mobile: '9000011111', email: 'sunita.rao@email.com', passwordHash: mockHashes.user4, status: 'UNDER_REVIEW', faceReferenceImages: [], createdAt: generatePastDate(50), adminNotes: ["Analyst requested more information regarding a medium-risk transaction."] },
        { id: 'user-5', name: 'Vikram Iyer', dob: '1998-05-20', mobile: '9821098765', email: 'vikram.iyer@email.com', passwordHash: mockHashes.user5, status: 'ACTIVE', faceReferenceImages: [], createdAt: generatePastDate(200), adminNotes: [] },
        { id: 'user-6', name: 'Meera Desai', dob: '1991-12-01', mobile: '9158234567', email: 'meera.desai@email.com', passwordHash: mockHashes.user6, status: 'ACTIVE', faceReferenceImages: [], createdAt: generatePastDate(900), adminNotes: [] },
        { id: 'user-7', name: 'Arjun Reddy', dob: '1993-07-18', mobile: '9945612378', email: 'arjun.reddy@email.com', passwordHash: mockHashes.user7, status: 'UNDER_REVIEW', faceReferenceImages: [], createdAt: generatePastDate(60), adminNotes: ["Unusual spending pattern detected. Account under review."] },
        { id: 'user-8', name: 'Fatima Khan', dob: '1985-02-14', mobile: '9876501234', email: 'fatima.khan@email.com', passwordHash: mockHashes.user8, status: 'BLOCKED', faceReferenceImages: [], createdAt: generatePastDate(1500), adminNotes: ["Account blocked following a failed biometric verification."] },
    ],
    bankDetails: [
        // Data for original users 1-4
        { userId: 'user-1', encryptedBankName: { iv: 'mockIV1', ciphertext: 'mockCiphertext' }, encryptedAccountNumber: { iv: 'mockIV2', ciphertext: 'mockCiphertext' }, encryptedBranchName: { iv: 'mockIV_br1', ciphertext: 'mockCiphertext' }, encryptedIfscCode: { iv: 'mockIV_ifsc1', ciphertext: 'mockCiphertext' }, encryptedAccountHolderName: { iv: 'mockIV_ahn1', ciphertext: 'mockCiphertext' }, encryptedAccountType: { iv: 'mockIV_at1', ciphertext: 'mockCiphertext' }, encryptedBranchAddress: { iv: 'mockIV_addr1', ciphertext: 'mockCiphertext' } },
        { userId: 'user-2', encryptedBankName: { iv: 'mockIV3', ciphertext: 'mockCiphertext' }, encryptedAccountNumber: { iv: 'mockIV4', ciphertext: 'mockCiphertext' }, encryptedBranchName: { iv: 'mockIV_br2', ciphertext: 'mockCiphertext' }, encryptedIfscCode: { iv: 'mockIV_ifsc2', ciphertext: 'mockCiphertext' }, encryptedAccountHolderName: { iv: 'mockIV_ahn2', ciphertext: 'mockCiphertext' }, encryptedAccountType: { iv: 'mockIV_at2', ciphertext: 'mockCiphertext' }, encryptedBranchAddress: { iv: 'mockIV_addr2', ciphertext: 'mockCiphertext' } },
        { userId: 'user-3', encryptedBankName: { iv: 'mockIV5', ciphertext: 'mockCiphertext' }, encryptedAccountNumber: { iv: 'mockIV6', ciphertext: 'mockCiphertext' }, encryptedBranchName: { iv: 'mockIV_br3', ciphertext: 'mockCiphertext' }, encryptedIfscCode: { iv: 'mockIV_ifsc3', ciphertext: 'mockCiphertext' }, encryptedAccountHolderName: { iv: 'mockIV_ahn3', ciphertext: 'mockCiphertext' }, encryptedAccountType: { iv: 'mockIV_at3', ciphertext: 'mockCiphertext' }, encryptedBranchAddress: { iv: 'mockIV_addr3', ciphertext: 'mockCiphertext' } },
        { userId: 'user-4', encryptedBankName: { iv: 'mockIV7', ciphertext: 'mockCiphertext' }, encryptedAccountNumber: { iv: 'mockIV8', ciphertext: 'mockCiphertext' }, encryptedBranchName: { iv: 'mockIV_br4', ciphertext: 'mockCiphertext' }, encryptedIfscCode: { iv: 'mockIV_ifsc4', ciphertext: 'mockCiphertext' }, encryptedAccountHolderName: { iv: 'mockIV_ahn4', ciphertext: 'mockCiphertext' }, encryptedAccountType: { iv: 'mockIV_at4', ciphertext: 'mockCiphertext' }, encryptedBranchAddress: { iv: 'mockIV_addr4', ciphertext: 'mockCiphertext' } },
        // Data for new users 5-8
        { userId: 'user-5', encryptedBankName: { iv: 'mockIV9', ciphertext: 'mockCiphertext' }, encryptedAccountNumber: { iv: 'mockIV10', ciphertext: 'mockCiphertext' }, encryptedBranchName: { iv: 'mockIV_br5', ciphertext: 'mockCiphertext' }, encryptedIfscCode: { iv: 'mockIV_ifsc5', ciphertext: 'mockCiphertext' }, encryptedAccountHolderName: { iv: 'mockIV_ahn5', ciphertext: 'mockCiphertext' }, encryptedAccountType: { iv: 'mockIV_at5', ciphertext: 'mockCiphertext' }, encryptedBranchAddress: { iv: 'mockIV_addr5', ciphertext: 'mockCiphertext' } },
        { userId: 'user-6', encryptedBankName: { iv: 'mockIV11', ciphertext: 'mockCiphertext' }, encryptedAccountNumber: { iv: 'mockIV12', ciphertext: 'mockCiphertext' }, encryptedBranchName: { iv: 'mockIV_br6', ciphertext: 'mockCiphertext' }, encryptedIfscCode: { iv: 'mockIV_ifsc6', ciphertext: 'mockCiphertext' }, encryptedAccountHolderName: { iv: 'mockIV_ahn6', ciphertext: 'mockCiphertext' }, encryptedAccountType: { iv: 'mockIV_at6', ciphertext: 'mockCiphertext' }, encryptedBranchAddress: { iv: 'mockIV_addr6', ciphertext: 'mockCiphertext' } },
        { userId: 'user-7', encryptedBankName: { iv: 'mockIV13', ciphertext: 'mockCiphertext' }, encryptedAccountNumber: { iv: 'mockIV14', ciphertext: 'mockCiphertext' }, encryptedBranchName: { iv: 'mockIV_br7', ciphertext: 'mockCiphertext' }, encryptedIfscCode: { iv: 'mockIV_ifsc7', ciphertext: 'mockCiphertext' }, encryptedAccountHolderName: { iv: 'mockIV_ahn7', ciphertext: 'mockCiphertext' }, encryptedAccountType: { iv: 'mockIV_at7', ciphertext: 'mockCiphertext' }, encryptedBranchAddress: { iv: 'mockIV_addr7', ciphertext: 'mockCiphertext' } },
        { userId: 'user-8', encryptedBankName: { iv: 'mockIV15', ciphertext: 'mockCiphertext' }, encryptedAccountNumber: { iv: 'mockIV16', ciphertext: 'mockCiphertext' }, encryptedBranchName: { iv: 'mockIV_br8', ciphertext: 'mockCiphertext' }, encryptedIfscCode: { iv: 'mockIV_ifsc8', ciphertext: 'mockCiphertext' }, encryptedAccountHolderName: { iv: 'mockIV_ahn8', ciphertext: 'mockCiphertext' }, encryptedAccountType: { iv: 'mockIV_at8', ciphertext: 'mockCiphertext' }, encryptedBranchAddress: { iv: 'mockIV_addr8', ciphertext: 'mockCiphertext' } },
    ],
    transactions: [
        // User 1 Transactions
        { id: 'txn-1', userId: 'user-1', userName: 'Rohan Sharma', recipient: 'Amazon.in', amount: 3200, type: 'UPI', location: null, locationName: 'Mumbai', time: generatePastDate(25, 14, 30), riskLevel: RiskLevel.Low, riskScore: 15, status: 'APPROVED', aiAnalysisLog: ['Recipient is a trusted merchant.', 'Amount is within usual spending range.'] },
        { id: 'txn-2', userId: 'user-1', userName: 'Rohan Sharma', recipient: 'Zomato', amount: 750, type: 'UPI', location: null, locationName: 'Mumbai', time: generatePastDate(22, 20, 0), riskLevel: RiskLevel.Low, riskScore: 10, status: 'APPROVED', aiAnalysisLog: ['Frequent merchant for user.', 'Low transaction amount.'] },
        { id: 'txn-3', userId: 'user-1', userName: 'Rohan Sharma', recipient: 'Unusual Vendor Inc.', amount: 25000, type: 'IMPS', location: null, locationName: 'Goa', time: generatePastDate(1, 11, 15), riskLevel: RiskLevel.High, riskScore: 85, status: 'FLAGGED_BY_USER', aiAnalysisLog: ['Recipient is new and unrecognized.', 'Amount is unusually high.', 'Transaction from a new location (Goa).'] },
        { id: 'txn-4', userId: 'user-1', userName: 'Rohan Sharma', recipient: 'Flipkart', amount: 1500, type: 'UPI', location: null, locationName: 'Mumbai', time: generatePastDate(5, 18, 45), riskLevel: RiskLevel.Low, riskScore: 12, status: 'APPROVED', aiAnalysisLog: ['Trusted e-commerce site.', 'Normal spending amount.'] },
        { id: 'txn-15', userId: 'user-1', userName: 'Rohan Sharma', recipient: 'Myntra', amount: 4500, type: 'UPI', location: null, locationName: 'Mumbai', time: generatePastDate(3, 16, 20), riskLevel: RiskLevel.Low, riskScore: 18, status: 'APPROVED', aiAnalysisLog: ['Frequent clothing merchant.', 'Amount is consistent with past purchases.'] },
        { id: 'txn-13', userId: 'user-1', userName: 'Rohan Sharma', recipient: 'BookMyShow', amount: 1200, type: 'UPI', location: null, locationName: 'Mumbai', time: generatePastDate(2, 19, 0), riskLevel: RiskLevel.Low, riskScore: 11, status: 'APPROVED', aiAnalysisLog: ['Standard entertainment purchase.'] },
        { id: 'txn-17', userId: 'user-1', userName: 'Rohan Sharma', recipient: 'Airtel Bill', amount: 999, type: 'UPI', location: null, locationName: 'Mumbai', time: generatePastDate(10), riskLevel: RiskLevel.Low, riskScore: 5, status: 'APPROVED', aiAnalysisLog: ['Recurring utility payment.'] },
        
        // User 2 Transactions
        { id: 'txn-5', userId: 'user-2', userName: 'Priya Patel', recipient: 'Netflix', amount: 649, type: 'UPI', location: null, locationName: 'Delhi', time: generatePastDate(28), riskLevel: RiskLevel.Low, riskScore: 5, status: 'APPROVED', aiAnalysisLog: ['Recurring subscription payment.', 'Known merchant.'] },
        { id: 'txn-6', userId: 'user-2', userName: 'Priya Patel', recipient: 'CryptoExchange', amount: 50000, type: 'NEFT', location: null, locationName: 'Unknown', time: generatePastDate(15, 3, 30), riskLevel: RiskLevel.Critical, riskScore: 95, status: 'BLOCKED_BY_AI', aiAnalysisLog: ['High-risk recipient category (Crypto).', 'Very large amount, first time transaction.', 'Location is unknown.', 'Transaction at unusual time (3:30 AM).'] },
        { id: 'txn-7', userId: 'user-2', userName: 'Priya Patel', recipient: 'Swiggy', amount: 450, type: 'UPI', location: null, locationName: 'Delhi', time: generatePastDate(2), riskLevel: RiskLevel.Low, riskScore: 8, status: 'APPROVED', aiAnalysisLog: ['Frequent food delivery service.'] },
        { id: 'txn-16', userId: 'user-2', userName: 'Priya Patel', recipient: 'Uber', amount: 320, type: 'UPI', location: null, locationName: 'Delhi', time: generatePastDate(4), riskLevel: RiskLevel.Low, riskScore: 9, status: 'APPROVED', aiAnalysisLog: ['Common transport expense.'] },
        { id: 'txn-14', userId: 'user-2', userName: 'Priya Patel', recipient: 'Apollo Pharmacy', amount: 800, type: 'UPI', location: null, locationName: 'Delhi', time: generatePastDate(1), riskLevel: RiskLevel.Low, riskScore: 14, status: 'APPROVED', aiAnalysisLog: ['Normal medical expense.'] },
        { id: 'txn-18', userId: 'user-2', userName: 'Priya Patel', recipient: 'New Cafe', amount: 1500, type: 'UPI', location: null, locationName: 'Jaipur', time: generatePastDate(8), riskLevel: RiskLevel.Medium, riskScore: 55, status: 'APPROVED', aiAnalysisLog: ['New recipient.', 'Transaction from a new city.'] },

        // User 3 Transactions (Blocked user)
        { id: 'txn-8', userId: 'user-3', userName: 'Amit Singh', recipient: 'Suspicious Site', amount: 12000, type: 'IMPS', location: null, locationName: 'Bangalore', time: generatePastDate(10), riskLevel: RiskLevel.High, riskScore: 88, status: 'BLOCKED_BY_AI', aiAnalysisLog: ['Recipient flagged in threat intelligence databases.', 'Unusual spending category for user.'] },
        { id: 'txn-9', userId: 'user-3', userName: 'Amit Singh', recipient: 'Foreign Transfer', amount: 75000, type: 'NEFT', location: null, locationName: 'Singapore', time: generatePastDate(9), riskLevel: RiskLevel.Critical, riskScore: 98, status: 'BLOCKED_BY_AI', aiAnalysisLog: ['Large international transfer is highly unusual.', 'Recipient country is a known risk zone.'] },
        
        // User 4 Transactions
        { id: 'txn-10', userId: 'user-4', userName: 'Sunita Rao', recipient: 'BigBasket', amount: 2200, type: 'UPI', location: null, locationName: 'Chennai', time: generatePastDate(18), riskLevel: RiskLevel.Low, riskScore: 20, status: 'APPROVED', aiAnalysisLog: ['Regular grocery purchase.'] },
        { id: 'txn-11', userId: 'user-4', userName: 'Sunita Rao', recipient: 'Mobile Recharge', amount: 599, type: 'UPI', location: null, locationName: 'Chennai', time: generatePastDate(12), riskLevel: RiskLevel.Low, riskScore: 10, status: 'APPROVED', aiAnalysisLog: ['Standard utility payment.'] },
        { id: 'txn-12', userId: 'user-4', userName: 'Sunita Rao', recipient: 'Odd Charity Donation', amount: 10000, type: 'IMPS', location: null, locationName: 'Kolkata', time: generatePastDate(6), riskLevel: RiskLevel.Medium, riskScore: 65, status: 'ESCALATED', aiAnalysisLog: ['One-time donation to a new recipient.', 'Amount is higher than average.', 'Location differs from user\'s primary city.'] },
        { id: 'txn-19', userId: 'user-4', userName: 'Sunita Rao', recipient: 'Adani Electricity', amount: 1800, type: 'UPI', location: null, locationName: 'Chennai', time: generatePastDate(3), riskLevel: RiskLevel.Low, riskScore: 8, status: 'APPROVED', aiAnalysisLog: ['Standard utility payment.'] },

        // User 5 Transactions
        { id: 'txn-20', userId: 'user-5', userName: 'Vikram Iyer', recipient: 'IRCTC', amount: 2500, type: 'UPI', location: null, locationName: 'Pune', time: generatePastDate(40), riskLevel: RiskLevel.Low, riskScore: 25, status: 'APPROVED', aiAnalysisLog: ['Train ticket booking from primary city.'] },
        { id: 'txn-21', userId: 'user-5', userName: 'Vikram Iyer', recipient: 'GPay to Friend', amount: 5000, type: 'UPI', location: null, locationName: 'Pune', time: generatePastDate(15), riskLevel: RiskLevel.Low, riskScore: 20, status: 'APPROVED', aiAnalysisLog: ['Peer-to-peer transfer.'] },
        { id: 'txn-22', userId: 'user-5', userName: 'Vikram Iyer', recipient: 'Croma Electronics', amount: 65000, type: 'NEFT', location: null, locationName: 'Pune', time: generatePastDate(2), riskLevel: RiskLevel.Medium, riskScore: 68, status: 'CLEARED_BY_ANALYST', aiAnalysisLog: ['High value purchase.', 'New high-ticket category for user.'] },

        // User 6 Transactions
        { id: 'txn-23', userId: 'user-6', userName: 'Meera Desai', recipient: 'IKEA', amount: 18000, type: 'IMPS', location: null, locationName: 'Hyderabad', time: generatePastDate(100), riskLevel: RiskLevel.Low, riskScore: 30, status: 'APPROVED', aiAnalysisLog: ['Home goods purchase.'] },
        { id: 'txn-24', userId: 'user-6', userName: 'Meera Desai', recipient: 'Blinkit', amount: 1200, type: 'UPI', location: null, locationName: 'Hyderabad', time: generatePastDate(10), riskLevel: RiskLevel.Low, riskScore: 10, status: 'APPROVED', aiAnalysisLog: ['Frequent grocery delivery.'] },
        { id: 'txn-25', userId: 'user-6', userName: 'Meera Desai', recipient: 'Online Gaming', amount: 7000, type: 'UPI', location: null, locationName: 'Hyderabad', time: generatePastDate(5), riskLevel: RiskLevel.Medium, riskScore: 45, status: 'APPROVED', aiAnalysisLog: ['New spending category.'] },

        // User 7 Transactions
        { id: 'txn-26', userId: 'user-7', userName: 'Arjun Reddy', recipient: 'Investment Co.', amount: 100000, type: 'RTGS', location: null, locationName: 'Bangalore', time: generatePastDate(50), riskLevel: RiskLevel.Medium, riskScore: 70, status: 'APPROVED', aiAnalysisLog: ['Large but verified investment.'] },
        { id: 'txn-27', userId: 'user-7', userName: 'Arjun Reddy', recipient: 'International Art Dealer', amount: 45000, type: 'NEFT', location: null, locationName: 'UK', time: generatePastDate(20), riskLevel: RiskLevel.High, riskScore: 92, status: 'BLOCKED_BY_AI', aiAnalysisLog: ['High value international transaction.', 'Unusual category.', 'First time international purchase.'] },
        { id: 'txn-28', userId: 'user-7', userName: 'Arjun Reddy', recipient: 'MakeMyTrip', amount: 35000, type: 'IMPS', location: null, locationName: 'Bangalore', time: generatePastDate(3), riskLevel: RiskLevel.Low, riskScore: 35, status: 'APPROVED', aiAnalysisLog: ['Travel booking from primary location.'] },

        // User 8 Transactions
        { id: 'txn-29', userId: 'user-8', userName: 'Fatima Khan', recipient: 'Local Kirana Store', amount: 300, type: 'UPI', location: null, locationName: 'Kolkata', time: generatePastDate(30), riskLevel: RiskLevel.Low, riskScore: 5, status: 'APPROVED', aiAnalysisLog: ['Typical local purchase.'] },
        { id: 'txn-30', userId: 'user-8', userName: 'Fatima Khan', recipient: 'Unknown UPI ID', amount: 9500, type: 'UPI', location: null, locationName: 'Unknown', time: generatePastDate(2), riskLevel: RiskLevel.Critical, riskScore: 96, status: 'BLOCKED_BY_AI', aiAnalysisLog: ['Transaction triggered biometric check.', 'Biometric verification failed.', 'Recipient is unknown.'] },

    ],
    verificationIncidents: [
        {
            id: 'inc-1',
            userId: 'user-8',
            userName: 'Fatima Khan',
            capturedImage: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAgACADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAn/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AA//Z', // Placeholder grey dot image
            timestamp: generatePastDate(2, 3, 45), // Occurred 2 days ago at 3:45 AM
            status: 'PENDING_REVIEW'
        }
    ],
    notifications: []
};

export default db;